version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client # Optional, for dynamic Python connection
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: "0.5"
