version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"  # expose to public
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: "0.5"
