version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"

  client1:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
