version: '3.8'

services:
  fl-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: fl-server
    volumes:
      - ./server_results:/app/results
    ports:
      - "8080:8080"
    environment:
      - MIN_FIT_CLIENTS=${MIN_FIT_CLIENTS}
      - MIN_AVAILABLE_CLIENTS=${MIN_AVAILABLE_CLIENTS}
      - NUM_ROUNDS=${NUM_ROUNDS}
    command: python server.py --rounds ${NUM_ROUNDS} --min_fit_clients ${MIN_FIT_CLIENTS} --min_available_clients ${MIN_AVAILABLE_CLIENTS} --output_dir /app/results
    restart: on-failure
    networks:
      - fl-network

networks:
  fl-network:
    driver: bridge