version: '3.8'

services:
  fl-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: fl-server
    volumes:
      - ./server_results:/app/results
    ports:
      - "8080:8080"
    environment:
      - MIN_FIT_CLIENTS=2
      - MIN_AVAILABLE_CLIENTS=2
      - NUM_ROUNDS=5
    command: python server.py --rounds ${NUM_ROUNDS:-5} --min_fit_clients ${MIN_FIT_CLIENTS:-2} --min_available_clients ${MIN_AVAILABLE_CLIENTS:-2} --output_dir /app/results
    restart: on-failure
    networks:
      - fl-network

networks:
  fl-network:
    driver: bridge