version: '3.8'

services:
  fl-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: fl-client-${CLIENT_ID}
    volumes:
      - ./client_results:/app/results
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
    command: >
      python client.py ${CLIENT_ID} --server ${SERVER_ADDRESS} --save --output_dir /app/results

    restart: on-failure