FROM python:3.10

RUN pip install --upgrade pip

WORKDIR /app

# Install Python dependencies
COPY requirements-client.txt .
RUN pip install -r requirements-client.txt

# Copy client code
COPY client.py .

# Make the directory for results
RUN mkdir -p /app/results

# Command will be specified in docker-compose.yml or at runtime