version: '3.8'

services:
  fl-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: fl-client-${CLIENT_ID}
    volumes:
      - ./client_results:/results
    environment:
      - CLIENT_ID
      - SERVER_ADDRESS
    command: >
      python client.py --cid $CLIENT_ID --server-address $SERVER_ADDRESS --result-dir ./results

    restart: on-failure